<?php
//
//
//namespace App\Tests\Functional\Api;
//
//use Symfony\Bundle\FrameworkBundle\KernelBrowser;
//use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
//use Symfony\Component\HttpFoundation\Request;
//use Symfony\Component\HttpFoundation\Response;
//
//class CustomerTest extends WebTestCase
//{
//    /** @var KernelBrowser  */
//    protected KernelBrowser $client;
//
//    /**
//     * @inheritDoc
//     */
//    protected function setUp(): void
//    {
//        parent::setUp();
//        $this->client = static::createClient();
//        $this->client->disableReboot();
//    }
//
//    public function testGetCustomers()
//    {
//        $this->client->request(Request::METHOD_GET, '/api/customers');
//        self::assertEquals(Response::HTTP_OK, $this->client->getResponse()->getStatusCode());
//    }
//
//    /**
//     * @inheritDoc
//     */
//    protected function tearDown(): void
//    {
//        parent::tearDown(); // TODO: Change the autogenerated stub
//    }
//}